1231-入金日の入力エラーを修正する
cocosumo/yumecoco-monorepo pull request #1250
Opened 2024-04-05 01:21 UTC by YokoHayakawa

## 変更

1. 入金日の入力に関わる処理を修正する

## 理由

1. closes #1231 

## テスト

- 入金日入力中にエラー終了しないこと

2024-04-05 01:33 UTC, YokoHayakawa commented
日付のクリックでの選択をした場合、１回目の選択が反映されないバグが見つかったため、一旦draftに戻します。

2024-04-05 02:28 UTC, Lorenzras requested changes

2024-04-05 02:28 UTC, Lorenzras commented on packages/kokoas-client/src/pages/projSearch/sections/result/details/paymentDetails/unissuedInvoiceAlert/AlertDialog.tsx
> +  const handleDateChange = (value: string) => {
valueの型はDateでした。

2024-04-05 02:28 UTC, Lorenzras commented on packages/kokoas-client/src/pages/projSearch/sections/result/details/paymentDetails/unissuedInvoiceAlert/AlertDialog.tsx
> +  const [paymentDate, setPaymentDate] = useState<string | null>(null);
そのまま Date　でいいかもしれません。

2024-04-05 02:29 UTC, Lorenzras requested changes
ケースによりますが、この場合、MUI の datepickerの onChangeの引数は Date型を返すようで、そのまま Dateでいいかもしれません。いかがでしょうか。

2024-04-05 03:04 UTC, YokoHayakawa commented on packages/kokoas-client/src/pages/projSearch/sections/result/details/paymentDetails/unissuedInvoiceAlert/AlertDialog.tsx
>    };
ご指摘ありがとうございます。
ファイル構成を修正していたため、getDisplayPaymentDate.tsにて
型変更に伴う修正なども見込んで対応しました。

2024-04-05 03:04 UTC, YokoHayakawa commented on packages/kokoas-client/src/pages/projSearch/sections/result/details/paymentDetails/unissuedInvoiceAlert/AlertDialog.tsx
> +  const handleDateChange = (value: string) => {
ご指摘ありがとうございます。
巻き戻しました。

2024-04-05 03:04 UTC, YokoHayakawa commented on packages/kokoas-client/src/pages/projSearch/sections/result/details/paymentDetails/unissuedInvoiceAlert/AlertDialog.tsx
> +  const [paymentDate, setPaymentDate] = useState<string | null>(null);
こちらも巻き戻しました

2024-04-05 03:06 UTC, YokoHayakawa commented
コメントと口頭での補足説明ありがとうございました。
見て頂いたタイミングと最終版でソフト構成が微妙に違っていたため、最終版に合わせて修正しました。
修正前の方が適切であれば、巻き戻しますので、すみませんがご確認をお願いいたします。

2024-04-05 04:57 UTC, Lorenzras approved these changes
LGTM!

2024-04-05 04:57 UTC, Lorenzras commented on packages/kokoas-client/src/pages/projSearch/sections/result/details/paymentDetails/unissuedInvoiceAlert/notifyAlertToCharwork/createMessage.ts
> +  const hasDisplayDate = getDisplayPaymentDate(paymentDate);
[hasは普段booleanに付ける](https://tamcom.jp/articles/naming-of-bool-methods)ので、他のところ同じように、以下でいいです。

```suggestion
  const displayDate = getDisplayPaymentDate(paymentDate);
```

2024-04-05 04:57 UTC, Lorenzras commented on packages/kokoas-client/src/pages/projSearch/sections/result/details/paymentDetails/unissuedInvoiceAlert/helper/getDisplayPaymentDate.test.ts
いいテストケースですね。当関数の仕様が明確になりました。

2024-04-05 04:57 UTC, Lorenzras commented on packages/kokoas-client/src/pages/projSearch/sections/result/details/paymentDetails/unissuedInvoiceAlert/saveReminder/convertToKintone.ts
> +    '' : `${format(new Date(paymentDate), 'yyyy-MM-dd')}`;
変更不要。

getDisplayPaymentDateと似てますね。以下の型にすれば、行けるかもしれません。

```
getDisplayPaymentDate(date: Date | null, format = "yyyy年M月d日") : string
```

`format` は任意で、デフォールトはよくあるパターンです。

2024-04-05 04:57 UTC, Lorenzras commented on packages/kokoas-client/src/pages/projSearch/sections/result/details/paymentDetails/unissuedInvoiceAlert/helper/getDisplayPaymentDate.ts
> +  return isValid(paymentDate) ? format(new Date(paymentDate), 'yyyy年M月d日') : '';
isValidで合格すると、生のDate型になり、datefns.format()で行けるかな。

```suggestion
  return isValid(paymentDate) ? format(paymentDate, 'yyyy年M月d日') : '';
```

2024-04-08 00:11 UTC, YokoHayakawa commented on packages/kokoas-client/src/pages/projSearch/sections/result/details/paymentDetails/unissuedInvoiceAlert/notifyAlertToCharwork/createMessage.ts
> +  const hasDisplayDate = getDisplayPaymentDate(paymentDate);
ご指摘ありがとうございます。
[a2771e1](https://github.com/cocosumo/yumecoco-monorepo/pull/1250/commits/a2771e15e2d88e109ccee897128ca031ee3a1ff0)にて修正しましたので、ご確認をお願いいたします。

2024-04-08 00:11 UTC, YokoHayakawa commented on packages/kokoas-client/src/pages/projSearch/sections/result/details/paymentDetails/unissuedInvoiceAlert/helper/getDisplayPaymentDate.test.ts
ありがとうございます！

2024-04-08 00:13 UTC, YokoHayakawa commented on packages/kokoas-client/src/pages/projSearch/sections/result/details/paymentDetails/unissuedInvoiceAlert/saveReminder/convertToKintone.ts
> +    '' : `${format(new Date(paymentDate), 'yyyy-MM-dd')}`;
ご指摘ありがとうございます。
上手くまとめられずに悩んでいた箇所で、参考にさせていただきました。
[a2771e1](https://github.com/cocosumo/yumecoco-monorepo/pull/1250/commits/a2771e15e2d88e109ccee897128ca031ee3a1ff0)にて修正しましたので、ご確認をお願いいたします。

2024-04-08 00:13 UTC, YokoHayakawa commented on packages/kokoas-client/src/pages/projSearch/sections/result/details/paymentDetails/unissuedInvoiceAlert/helper/getDisplayPaymentDate.ts
> +  return isValid(paymentDate) ? format(new Date(paymentDate), 'yyyy年M月d日') : '';
ご指摘ありがとうございます。
動作テストも問題なかったため、上記の通り修正しました。
[a2771e1](https://github.com/cocosumo/yumecoco-monorepo/pull/1250/commits/a2771e15e2d88e109ccee897128ca031ee3a1ff0)にて、ご確認をお願いいたします。

2024-04-08 00:58 UTC, Lorenzras approved these changes
変更のコードレビューをしました！LGTM。

2024-04-08 00:58 UTC, merged