1506-請求項目と金額が空だと保存できないようにする
cocosumo/yumecoco-monorepo pull request #1509
Opened 2024-06-25 03:36 UTC by YokoHayakawa

## 変更

1. タイトルのとおり

## 理由

1. closes #1506 

## テスト

- ブラウザにて確認

2024-06-25 03:54 UTC, YokoHayakawa commented on packages/kokoas-client/src/pages/projInvoiceV2/hooks/useSaveHandler.ts
> +      } else {
zodのバリデーションを活用できていない

2024-06-25 12:29 UTC, Lorenzras requested changes
別件ですが、金額をバリデーションには z.coerse.number()にするか、変換処理で対応するかになります。

変更の依頼していますが、強制マージするかどうかお任せします！

2024-06-25 12:29 UTC, Lorenzras commented on packages/kokoas-client/src/pages/projInvoiceV2/hooks/useSaveHandler.ts
>        const [key, errorField] = Object.entries(errors)[0]; // Show first validation error instance
確か、配列の場合、messageはerrorField内のrootにあります。console.logに出力すると構成がわかります。
エラーアラートも調整してください。

2024-06-25 12:29 UTC, Lorenzras commented on packages/kokoas-client/src/pages/projInvoiceV2/hooks/useSaveHandler.ts
> +      } else {
確認したところ、zodのarrayのバリデーションが機能しています。

複雑なバリデーションはrefineやsuperRefineが使えます。

例えば：金額が入っている行が最低でも1行必要です。
要点は以下のような感じですが、要件に沿って実装してください。

```typescript
const schema = z.object({
    amounts: z.array(amounts).min(1, {message: "空！"})
}).superRefine((data, ctx)=> {

  const hasAtleastOneAmount = data.amounts.some((amt) => amt.billAmount);

  if(!hastAtleastOneAmount) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message: '金額が入っている行が最低でも1行必要',
        path: ['amounts.0'],
      });
  }

})
```

projRegisterV2が参考になるかも知れません。

2024-06-26 03:42 UTC, YokoHayakawa commented on packages/kokoas-client/src/pages/projInvoiceV2/hooks/useSaveHandler.ts
> +      } else {
参考ロジック、ありがとうございます！
記載して頂いた要点とprojRegisterV2を参考に、なんとか修正できました。

2024-06-26 03:48 UTC, YokoHayakawa commented on packages/kokoas-client/src/pages/projInvoiceV2/hooks/useSaveHandler.ts
>        const [key, errorField] = Object.entries(errors)[0]; // Show first validation error instance
コメントありがとうございます。おかげでエラーアラートも修正できました。

余談ですが、
配列内がobjectなせいか、rootの代わりにobjectのkeyが使用されていました。
はじめ確認していた時はrootでしたが、エラー箇所のhelperTextがうまく反映されなかったことの対策で、zodのpathでobject内の要素まで指定したせいかな、と思います。

2024-06-26 03:55 UTC, YokoHayakawa commented on packages/kokoas-client/src/pages/projInvoiceV2/hooks/useSaveHandler.ts
まさに苦肉の策の逃げ道でした…
ラスさんのおかげで、元々考えていた内容でバリデーションとエラーメッセージが出せたので、この処理は巻き戻しました。
サポートとても助かりました！ありがとうございます。

2024-06-26 04:00 UTC, YokoHayakawa commented
>別件ですが、金額をバリデーションには z.coerse.number()にするか、変換処理で対応するかになります。

調べてみましたが、これとても良いですね。
今回はロジック内で変換処理してしまっていますが、今後活用させてもらおうと思います！

2024-06-26 04:07 UTC, YokoHayakawa commented
@Lorenzras 
useSaveHandler()のエラーアラートの部分、やや不安が残るので、すみませんが確認してもらっても良いでしょうか？
時間取るの難しければ、こちらで対応するので、無理はしなくて大丈夫です！

2024-06-26 11:16 UTC, Lorenzras approved these changes
コードを確認しました。
画面上でざっくり触って、問題ないと思います。

ただ、金額に数字じゃないものを入れると、落ちてしまいます。

転職前に、ランタイムエラーが派生したら、システム全体的のハンドラーを組んでましたが、実装せず、ローカルブランチ残っていると思います。今まで通り、個別対応になります。

2024-06-26 11:34 UTC, Lorenzras commented on packages/kokoas-client/src/pages/projInvoiceV2/hooks/useSaveHandler.ts
色々な背景はありますが、コードの仕組みと理由をコメントで残していただいたので、いいと思います。
レビュワーがいれば、指摘によって修正されますが、色々な原因でよくあるものです。

2024-06-27 01:25 UTC, YokoHayakawa commented
@Lorenzras 
ご確認ありがとうございます！
> ただ、金額に数字じゃないものを入れると、落ちてしまいます。

ここは私も昨日気付きまして、#1415 にて対策しました。
このPRマージ後にmasterに入れようと思います。

2024-06-27 01:25 UTC, merged